name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.18.2'

      - name: Install dependencies
        run: npm install

      # - name: Run tests
      #   run: npm test
      - name: Deploy to localhost
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo "Deploying to localhost..."
          # Add your deployment steps here
          # For example, start your local server
          npm run dev &
          node backend/server &
      
